import 'package:flutter/material.dart';

List productlist=[
  {
    'name':'',
    'Brand':'',
    'image':'assets/image/p1.png',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'assets/image/p2.png',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'assets/image/p3.png',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'assets/image/p4.png',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'assets/image/p5.png',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'assets/image/p6.png',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'assets/image/p7.jpg',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
];