import 'package:flutter/material.dart';

List productlist=[
  {
    'name':'',
    'Brand':'',
    'image':'assets/image/p1.jpg',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'assets/image/p4.jpg',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'assets/image/p2.jpg',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'assets/image/p3.jpg',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'assets/image/p5.jpg',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'assets/image/p6.jpg',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'assets/image/p7.jpg',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
  {
    'name':'',
    'Brand':'',
    'image':'',
    'price':4,
    'description':""
  },
];